### ISSUE TITLE
why percentile rank don't have zero?

### ISSUE THREAD

**Issue by ZhengTzer** [frieds/frieds.github.io#2]
i was refer to your post @https://dfrieds.com/data-analysis/rank-method-python-pandas
the last example @df_quiz_scores

one thing i don't understand, Jill get 100 marks, percentile rank is 100, i get it.
but why jill get 65 mark, yet the percentile rank is at 9? and not zero?

thanks

**Comment by frieds** [comment]
Here is the ranking process with the 'average' method for a more simplified example:

First, sort the quiz scores in ascending order: [75, 76, 84, 85, 90, 90, 93]
Assign a rank to each score, starting from 1. If there are duplicate scores, average their rank values:
75: rank 1
76: rank 2
84: rank 3
85: rank 4
90: rank 5 and 6 (average rank: 5.5)
90: rank 5 and 6 (average rank: 5.5)
93: rank 7
Compute the percentile rank by dividing the rank value by the total number of scores:
75: 1/7 ≈ 0.142857
76: 2/7 ≈ 0.285714
84: 3/7 ≈ 0.428571
85: 4/7 ≈ 0.571429
90: 5.5/7 ≈ 0.785714
90: 5.5/7 ≈ 0.785714
93: 7/7 = 1.000000
With the 'average' method, the rank values are averaged for duplicate scores, resulting in non-integer rank values (e.g., 5.5 for both 90 scores in this example). The percentile rank is then calculated by dividing the rank value by the total number of scores, giving a value between 0 and 1, inclusive.
